### ISSUE TITLE
How to take / compare screenshots in different resolutions in a single test?

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/sudoku-applitools#1]
It could be nice to do

```js
describe('Sudoku', () => {
  it('works', () => {
    cy.visit('/')
    // on easy setting there are 45 filled cells at the start
    cy.get('.game__cell--filled').should('have.length', 45)
    cy.contains('.status__time', '00:00')
    cy.contains('.status__difficulty-select', 'Easy')

    cy.eyesCheckWindow({ tag: 'desktop' })

    cy.viewport(600, 800)
    cy.get('.game__cell--filled').should('have.length', 45)

    // how to vary the resolution of individual screenshots?
    // cy.eyesCheckWindow({ tag: 'tablet' })

    cy.viewport(300, 600)
    cy.get('.game__cell--filled').should('have.length', 45)
    // cy.eyesCheckWindow({ tag: 'mobile' })
  })
})
```

Or does it have to be 3 different tests that control the viewport from outside? Do they need to `open` and `close` eyes for every resolution?

**Comment by giltayar** [comment]
https://www.npmjs.com/package/@applitools/eyes-cypress#configuring-the-browser

You configure the set of browser configurations (browser + viewport size) in the `eyes.open` or in the `applitools.config.js` and it will take a screenshot of the page in that browser configuration. No need to set the viewport size, because we're not really taking a screenshot on the local computer, but only taking a dom snapshot that is sent to the visual grid, to be used to take screenshots in the various browser configurations you specified.

**Comment by giltayar** [comment]
Fixed with latest push
